/**
 * Curated intent ids from ontology/intents/*.yaml.
 *
 * The per-intent regex matchers that used to live here (INTENT_MATCHERS /
 * matchEndpointsForIntent) are gone: endpoint→intent binding is now semantic
 * (see embed/bind-endpoints.ts — cosine similarity + floor), which is both more
 * accurate and scales without per-intent rules. Only the id list remains, used
 * to scope materialization and binding to the curated set.
 */
export const CURATED_INTENT_IDS = [
  "ai.image_generate",
  "ai.llm_complete",
  "ai.speech_to_text",
  "ai.text_to_speech",
  "ai.embeddings",
  "ai.web_research",
  "ai.document_extract",
  "shop.inflation_tracker",
  "cloud.domains",
  "comms.agent_inbox",
  "comms.send_email",
  "comms.send_fax",
  "comms.voice_call",
  "blockchain.rpc",
  "compute.convert_units",
  "compute.financial_calculator",
  "identity.company_enrich",
  "compute.compute_answer",
  "utility.email_validate",
  "finance.exchange_rates",
  "data.agriculture_stats",
  "blockchain.airdrop_tracker",
  "data.gov_civic",
  "identity.gov_records",
  "identity.lei_lookup",
  "data.book_lookup",
  "data.drug_label",
  "data.holidays_lookup",
  "blockchain.nft_metadata",
  "data.news_headlines",
  "data.sports_scores",
  "utility.iban_validate",
  "utility.vat_validate",
  "data.scientific_lookup",
  "data.code_repository",
  "data.ip_lookup",
  "data.job_search",
  "identity.person_search",
  "ai.ocr",
  "utility.phone_validate",
  "ai.translate_text",
  "data.weather_forecast",
  "web.scrape",
  "data.whois_lookup",
  "devtools.captcha_solve",
  "devtools.pdf_manipulate",
  "devtools.webhook_tools",
  "finance.crypto_market_intel",
  "finance.crypto_spot_price",
  "blockchain.defi_analytics",
  "blockchain.onchain_analytics",
  "finance.stock_quote",
  "blockchain.token_balance",
  "finance.prediction_markets",
  "finance.trading_signals",
  "finance.economic_data",
  "finance.market_data",
  "finance.stablecoin_monitor",
  "maps.places",
  "maps.geocode",
  "shop.competitive_landscape",
  "social.social_data",
  "media.movie_lookup",
  "media.anime_lookup",
  "comms.send_sms",
  "realestate.property_lookup",
  "web.search",
  "shop.compare_price",
  "shop.find_deals",
  "shop.tcg_catalog",
  "shop.price_drop_alert",
  "shop.track_price_history",
  "social.influencer_search",
  "cloud.hosting",
  "agent.memory",
  "agent.marketplace",
  "travel.place_reviews",
  "travel.aviation",
  "web.markdown_extract",
  "web.screenshot",
  // Coverage additions — clusters surfaced by the orphan audit (see ontology/intents/*.yaml).
  "ai.moderate_content",
  "ai.token_count",
  "blockchain.network_metrics",
  "data.pii_detect",
  "devtools.generate_secret",
  "devtools.file_convert",
  "media.transcode",
] as const;

export type CuratedIntentId = (typeof CURATED_INTENT_IDS)[number];
