#!/usr/bin/env node
// Dev-time only: distill all-the-cities (a devDependency) into a committed, filtered gazetteer for the
// Place extractor. Population >= 100k, minus common-word city names that would false-fire even Title-Cased.
// Output src/entity/world-cities.ts ships (via tsc -> dist); all-the-cities does NOT ship to the server.
import cities from "all-the-cities";
import { writeFile } from "node:fs/promises";
const arr = Array.isArray(cities) ? cities : (cities.default || []);
// city names that are also common English words / months — drop even at pop>=100k (Title-Case at a
// sentence start would otherwise mis-fire). "York" kept (near-always a place).
const STOP = new Set(["nice","split","reading","mobile","man","sale","surprise","best","long","hope",
  "center","centre","industry","boring","same","general","mission","union","of","as","a","an","the",
  "why","does","will","march","may","june","july","august","clinton","independence","liberty","concord"]);
const fold = (s) => s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase().trim();
const names = new Set();
const add = (raw) => {
  const n = fold(String(raw || ""));
  if (n.length < 3 || STOP.has(n)) return;
  if (!/^[a-z][a-z0-9'. -]*$/.test(n)) return; // accent-folded ascii; skip scripts we can't case-match
  names.add(n);
};
for (const c of arr) {
  if (c.population < 100000) continue;
  add(c.name);
  for (const alt of String(c.altName || "").split(",")) if (alt.trim()) add(alt); // English/alt spellings (Ghent, Cluj)
}
const sorted = [...names].sort();
const body = `// GENERATED by scripts/generate-cities.mjs — do not edit. Source: all-the-cities (pop >= 100k).\n`
  + `// ${sorted.length} world cities for supplemental Place detection (Title-Case / after-preposition gated).\n`
  + `export const WORLD_CITIES: ReadonlySet<string> = new Set(${JSON.stringify(sorted)});\n`;
await writeFile("src/entity/world-cities.ts", body);
console.log(`wrote src/entity/world-cities.ts with ${sorted.length} cities`);
